### ISSUE TITLE
Could not build all modules with target STC15F104E

### ISSUE THREAD

**Issue by tpimh** [laborer/c51drv#1]
When I run `make TARGET=STC15F104E` the compilation fails for me because of:
- uart2 module (multiple problems)
- stc_gpio, stc_adc and stc_pca demos (linking problems)
- stc_spi demo (function 'delay_ms' implicit declaration)
- stc_uart2 demo (because uart2 module could not be built)

Could you please help me fixing it?

**Comment by laborer** [comment]
Thanks for the bug report.  STC15F uses a different timer for UART2 than STC12C causing the compilation problem.  This has been fixed in the trunk.

**Comment by tpimh** [comment]
Thank you.
